spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/board
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect