-- drop table if exists ROLES cascade;
-- drop table if exists USERS cascade;
-- drop table if exists POSTS cascade;
-- drop table if exists COMMENTS cascade;
-- drop table if exists USERS_ROLES cascade;
--
-- drop sequence if exists COMMENT_SEQUENCE ;
-- drop sequence if exists POST_SEQUENCE ;
-- drop sequence if exists ROLE_SEQUENCE ;
-- drop sequence if exists USER_SEQUENCE ;

CREATE SEQUENCE IF NOT EXISTS COMMENT_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS POST_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS ROLE_SEQUENCE START WITH 10 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS USER_SEQUENCE START WITH 10 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS ROLES
(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS
(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(200) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS
(
    ID SERIAL PRIMARY KEY,
    HEADER VARCHAR(200),
    TEXT VARCHAR(200),
    CREATED_AT TIMESTAMP,
    USER_ID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID SERIAL PRIMARY KEY,
    TEXT VARCHAR(200),
    USER_ID INTEGER REFERENCES USERS(ID),
    POST_ID INTEGER REFERENCES POSTS(ID)
);

CREATE TABLE IF NOT EXISTS USERS_ROLES
(
    USER_ID INTEGER REFERENCES USERS(ID),
    ROLE_ID INTEGER REFERENCES ROLES(ID)
);

